[2022-06-10 20:00:01,045]-[ERROR] [run_job - 131- Job "plane_update (trigger: interval[6:00:00], next run at: 2022-06-11 02:00:00 CST)" raised an exception]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\民航行程推荐\wsgi.py", line 542, in plane_update
    Function.planes_Update_Function()  # 执行数据库更新函数
  File "D:\民航行程推荐\Function.py", line 133, in planes_Update_Function
    city, index, numbers = i
ValueError: not enough values to unpack (expected 3, got 2)
[2022-06-10 20:00:01,055]-[ERROR] [listen_error - 554- 数据库更新时出现了错误!]
[2022-06-11 02:00:01,034]-[ERROR] [run_job - 131- Job "plane_update (trigger: interval[6:00:00], next run at: 2022-06-11 08:00:00 CST)" raised an exception]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\民航行程推荐\wsgi.py", line 542, in plane_update
    Function.planes_Update_Function()  # 执行数据库更新函数
  File "D:\民航行程推荐\Function.py", line 133, in planes_Update_Function
    city, index, numbers = i
ValueError: not enough values to unpack (expected 3, got 2)
[2022-06-11 02:00:01,034]-[ERROR] [listen_error - 554- 数据库更新时出现了错误!]
[2022-06-11 08:00:01,038]-[ERROR] [run_job - 131- Job "plane_update (trigger: interval[6:00:00], next run at: 2022-06-11 14:00:00 CST)" raised an exception]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\民航行程推荐\wsgi.py", line 542, in plane_update
    Function.planes_Update_Function()  # 执行数据库更新函数
  File "D:\民航行程推荐\Function.py", line 133, in planes_Update_Function
    city, index, numbers = i
ValueError: not enough values to unpack (expected 3, got 2)
[2022-06-11 08:00:01,038]-[ERROR] [listen_error - 554- 数据库更新时出现了错误!]
[2022-06-11 14:00:01,023]-[ERROR] [run_job - 131- Job "plane_update (trigger: interval[6:00:00], next run at: 2022-06-11 20:00:00 CST)" raised an exception]
Traceback (most recent call last):
<<<<<<< HEAD
  File "D:\Python3.10.4\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\民航行程推荐\wsgi.py", line 542, in plane_update
    Function.planes_Update_Function()  # 执行数据库更新函数
  File "D:\民航行程推荐\Function.py", line 133, in planes_Update_Function
    city, index, numbers = i
ValueError: not enough values to unpack (expected 3, got 2)
[2022-06-11 14:00:01,023]-[ERROR] [listen_error - 554- 数据库更新时出现了错误!]
=======
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 252, in index_ajax1
    economy_class,First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mUnknown attribute 'astype' of type [unichr x 32]
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i] = result[i][8].astype(int)
[0m        [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at D:\民航行程推荐\Function.py (83)[0m
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i] = result[i][8].astype(int)
[0m        [1m^[0m[0m

[2022-05-25 15:05:38,481]-[ERROR] [log_exception - 1455- Exception on /index_ajax1 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 252, in index_ajax1
    economy_class,First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mUnknown attribute 'astype' of type [unichr x 32]
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i][8] = result[i][8].astype(int)
[0m        [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at D:\民航行程推荐\Function.py (83)[0m
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i][8] = result[i][8].astype(int)
[0m        [1m^[0m[0m

[2022-05-25 16:16:30,919]-[ERROR] [decorated_function - 487- Exception possibly due to cache backend.]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask_caching\__init__.py", line 479, in decorated_function
    self.cache.set(
  File "D:\Python3.10.4\lib\site-packages\flask_caching\backends\simplecache.py", line 101, in set
    item = (expires, pickle.dumps(value, pickle.HIGHEST_PROTOCOL))
TypeError: cannot pickle 'coroutine' object
[2022-05-25 16:16:30,923]-[ERROR] [log_exception - 1455- Exception on /login [GET]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1734, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
[2022-05-25 16:18:09,569]-[ERROR] [decorated_function - 487- Exception possibly due to cache backend.]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask_caching\__init__.py", line 479, in decorated_function
    self.cache.set(
  File "D:\Python3.10.4\lib\site-packages\flask_caching\backends\simplecache.py", line 101, in set
    item = (expires, pickle.dumps(value, pickle.HIGHEST_PROTOCOL))
TypeError: cannot pickle 'coroutine' object
[2022-05-25 16:18:09,571]-[ERROR] [log_exception - 1455- Exception on /login [GET]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1734, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
[2022-05-28 06:41:39,094]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /login_ajax1]
[2022-05-28 06:41:39,094]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-28 08:33:29,695]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /settlement_ajax]
[2022-05-28 08:33:29,695]-[WARNING] [encounter_403 - 116- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-28 08:41:14,054]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /settlement_ajax]
[2022-05-28 08:41:14,054]-[WARNING] [encounter_403 - 116- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-28 10:57:26,547]-[ERROR] [log_exception - 1455- Exception on /index_ajax31 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 346, in index_ajax3
    informations = json.loads(request.form.get('informations'))
  File "D:\Python3.10.4\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-05-28 10:58:58,592]-[ERROR] [log_exception - 1455- Exception on /index_ajax31 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 346, in index_ajax3
    informations = json.loads(request.form.get('informations'))
  File "D:\Python3.10.4\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-05-28 11:00:12,696]-[ERROR] [log_exception - 1455- Exception on /index_ajax31 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 348, in index_ajax3
    informations = json.loads(request.form.get('informations'))
  File "D:\Python3.10.4\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-05-28 11:01:39,597]-[ERROR] [log_exception - 1455- Exception on /index_ajax31 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 348, in index_ajax3
    informations = json.loads(request.form.get('informations'))
  File "D:\Python3.10.4\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-05-28 11:02:41,110]-[ERROR] [log_exception - 1455- Exception on /index_ajax31 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 348, in index_ajax3
    informations = json.loads(request.form.get('informations'))
  File "D:\Python3.10.4\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-05-28 11:06:26,564]-[ERROR] [log_exception - 1455- Exception on /settlement_ajax [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 446, in settlement_ajax
    session.pop(f'table{i}')
  File "D:\Python3.10.4\lib\site-packages\werkzeug\datastructures.py", line 216, in pop
    rv = super().pop(key)
KeyError: 'table0'
[2022-05-28 11:19:21,065]-[ERROR] [log_exception - 1455- Exception on /index_ajax32 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 407, in index_ajax32
    economy_class, First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(float64, Literal[int](8))
 
There are 22 candidate implementations:
[1m      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(float64, int64)':[0m
[1m       No match.[0m
[0m
[0m[1mDuring: typing of intrinsic-call at D:\民航行程推荐\Function.py (92)[0m
[0m[1mDuring: typing of static-get-item at D:\民航行程推荐\Function.py (92)[0m
[1m
File "Function.py", line 92:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
        for j in range(i+1, len(result)):
[1m            if len(result[index][8]) > len(result[j][8]) or (len(result[index][8]) == len(result[j][8]) and result[index][8] > result[j][8]):
[0m            [1m^[0m[0m

[2022-05-28 11:22:46,455]-[ERROR] [log_exception - 1455- Exception on /index_ajax32 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 407, in index_ajax32
    economy_class, First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(float64, Literal[int](8))
 
There are 22 candidate implementations:
[1m      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(float64, int64)':[0m
[1m       No match.[0m
[0m
[0m[1mDuring: typing of intrinsic-call at D:\民航行程推荐\Function.py (92)[0m
[0m[1mDuring: typing of static-get-item at D:\民航行程推荐\Function.py (92)[0m
[1m
File "Function.py", line 92:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
        for j in range(i+1, len(result)):
[1m            if len(str(result[index][8])) > len(str(result[j][8])) or \
[0m            [1m^[0m[0m

[2022-05-28 11:26:37,950]-[ERROR] [log_exception - 1455- Exception on /index_ajax32 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 407, in index_ajax32
    economy_class, First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(float64, Literal[int](8))
 
There are 22 candidate implementations:
[1m      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(float64, int64)':[0m
[1m       No match.[0m
[0m
[0m[1mDuring: typing of intrinsic-call at D:\民航行程推荐\Function.py (92)[0m
[0m[1mDuring: typing of static-get-item at D:\民航行程推荐\Function.py (92)[0m
[1m
File "Function.py", line 92:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
        for j in range(i+1, len(result)):
[1m            if len(str(result[index][8])) > len(str(result[j][8])) or \
[0m            [1m^[0m[0m

[2022-05-28 11:30:47,481]-[ERROR] [log_exception - 1455- Exception on /index_ajax32 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 389, in index_ajax32
    a = Thread_Pool.submit(Function.select_planes, informations[num])
IndexError: list index out of range
[2022-05-28 11:41:25,015]-[ERROR] [log_exception - 1455- Exception on /settlement_ajax [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 448, in settlement_ajax
    session.pop(f'table{i+1}')
  File "D:\Python3.10.4\lib\site-packages\werkzeug\datastructures.py", line 216, in pop
    rv = super().pop(key)
KeyError: 'table1'
[2022-05-28 11:41:35,554]-[ERROR] [log_exception - 1455- Exception on /settlement_ajax [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 448, in settlement_ajax
    session.pop(f'table{i+1}')
  File "D:\Python3.10.4\lib\site-packages\werkzeug\datastructures.py", line 216, in pop
    rv = super().pop(key)
KeyError: 'table1'
[2022-05-28 11:42:05,522]-[ERROR] [log_exception - 1455- Exception on /settlement_ajax [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 448, in settlement_ajax
    session.pop(f'table{i+1}')
  File "D:\Python3.10.4\lib\site-packages\werkzeug\datastructures.py", line 216, in pop
    rv = super().pop(key)
KeyError: 'table1'
[2022-05-28 16:17:17,075]-[ERROR] [log_exception - 1455- Exception on /index_ajax32 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 408, in index_ajax32
    economy_class, First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(float64, Literal[int](8))
 
There are 22 candidate implementations:
[1m      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(float64, int64)':[0m
[1m       No match.[0m
[0m
[0m[1mDuring: typing of intrinsic-call at D:\民航行程推荐\Function.py (92)[0m
[0m[1mDuring: typing of static-get-item at D:\民航行程推荐\Function.py (92)[0m
[1m
File "Function.py", line 92:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
        for j in range(i+1, len(result)):
[1m            if len(str(result[index][8])) > len(str(result[j][8])) or \
[0m            [1m^[0m[0m

[2022-05-28 16:18:12,272]-[ERROR] [log_exception - 1455- Exception on /index_ajax32 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 408, in index_ajax32
    economy_class, First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(float64, Literal[int](8))
 
There are 22 candidate implementations:
[1m      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(float64, int64)':[0m
[1m       No match.[0m
[0m
[0m[1mDuring: typing of intrinsic-call at D:\民航行程推荐\Function.py (92)[0m
[0m[1mDuring: typing of static-get-item at D:\民航行程推荐\Function.py (92)[0m
[1m
File "Function.py", line 92:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
        for j in range(i+1, len(result)):
[1m            if len(str(result[index][8])) > len(str(result[j][8])) or \
[0m            [1m^[0m[0m

>>>>>>> 1ddb831b49a9d34d0b11c014abc114e5906e0f71
