[2022-05-22 16:23:22,451]-[ERROR] [log_exception - 1455- Exception on /settlement [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 376, in settlement
    emails = json.loads(request.form.get('emails'))
  File "D:\Python3.10.4\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-05-24 18:08:12,065]-[ERROR] [log_exception - 1455- Exception on /login [GET]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Python3.10.4\lib\site-packages\flask_caching\__init__.py", line 475, in decorated_function
    rv = f(*args, **kwargs)
  File "D:\民航行程推荐\wsgi.py", line 116, in login
    session['test'] = Function.create_String(100)
  File "D:\民航行程推荐\Function.py", line 48, in create_String
    return ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', n))
  File "D:\Python3.10.4\lib\random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
[2022-05-25 07:15:56,907]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /settlement]
[2022-05-25 07:15:56,907]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 07:18:22,452]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /settlement]
[2022-05-25 07:18:22,452]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 07:20:57,156]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 07:53:02,233]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /login_ajax2]
[2022-05-25 07:53:02,233]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 07:53:29,478]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 07:53:41,984]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:11,676]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:16,284]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:29,468]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:47,565]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:48,331]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:55,512]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:55,969]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:56,129]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:56,296]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:58,605]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 09:25:59,934]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 14:38:57,826]-[ERROR] [log_exception - 1455- Exception on /index_ajax1 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 252, in index_ajax1
    economy_class,First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<class 'int'>) found for signature:
 
 >>> int([unichr x 32])
 
There are 2 candidate implementations:
[1m     - Of which 2 did not match due to:
     Overload of function 'int': File: numba\core\typing\builtins.py: Line 953.
       With argument(s): '([unichr x 32])':[0m
[1m      No match.[0m
[0m
[0m[1mDuring: resolving callee type: Function(<class 'int'>)[0m
[0m[1mDuring: typing of call at D:\民航行程推荐\Function.py (85)
[0m
[1m
File "Function.py", line 85:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
        for j in range(i+1, len(result)):
[1m            if int(result[index][8]) > int(result[j][8]):
[0m            [1m^[0m[0m

[2022-05-25 14:42:27,479]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /login_ajax1]
[2022-05-25 14:42:27,480]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 14:42:30,327]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /login_ajax1]
[2022-05-25 14:42:30,328]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
[2022-05-25 15:03:49,445]-[ERROR] [log_exception - 1455- Exception on /index_ajax1 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 252, in index_ajax1
    economy_class,First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mUnknown attribute 'astype' of type [unichr x 32]
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i] = result[i][8].astype(int)
[0m        [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at D:\民航行程推荐\Function.py (83)[0m
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i] = result[i][8].astype(int)
[0m        [1m^[0m[0m

[2022-05-25 15:05:38,481]-[ERROR] [log_exception - 1455- Exception on /index_ajax1 [POST]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\民航行程推荐\wsgi.py", line 252, in index_ajax1
    economy_class,First_class = b.result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Python3.10.4\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Python3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python3.10.4\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mUnknown attribute 'astype' of type [unichr x 32]
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i][8] = result[i][8].astype(int)
[0m        [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at D:\民航行程推荐\Function.py (83)[0m
[1m
File "Function.py", line 83:[0m
[1mdef sort_planes_cost(result)->tuple:#按价格升序
    <source elided>
    for i in range(len(result)):
[1m        result[i][8] = result[i][8].astype(int)
[0m        [1m^[0m[0m

[2022-05-25 16:16:30,919]-[ERROR] [decorated_function - 487- Exception possibly due to cache backend.]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask_caching\__init__.py", line 479, in decorated_function
    self.cache.set(
  File "D:\Python3.10.4\lib\site-packages\flask_caching\backends\simplecache.py", line 101, in set
    item = (expires, pickle.dumps(value, pickle.HIGHEST_PROTOCOL))
TypeError: cannot pickle 'coroutine' object
[2022-05-25 16:16:30,923]-[ERROR] [log_exception - 1455- Exception on /login [GET]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1734, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
[2022-05-25 16:18:09,569]-[ERROR] [decorated_function - 487- Exception possibly due to cache backend.]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask_caching\__init__.py", line 479, in decorated_function
    self.cache.set(
  File "D:\Python3.10.4\lib\site-packages\flask_caching\backends\simplecache.py", line 101, in set
    item = (expires, pickle.dumps(value, pickle.HIGHEST_PROTOCOL))
TypeError: cannot pickle 'coroutine' object
[2022-05-25 16:18:09,571]-[ERROR] [log_exception - 1455- Exception on /login [GET]]
Traceback (most recent call last):
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "D:\Python3.10.4\lib\site-packages\flask\app.py", line 1734, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
[2022-05-28 06:41:39,094]-[WARNING] [validate - 344- Forbidden (CSRF token missing or incorrect.): /login_ajax1]
[2022-05-28 06:41:39,094]-[WARNING] [encounter_403 - 115- 出现了403,可能是遇到了爬虫或是csrf令牌错误!]
